import { useEffect, useState, type FormEvent } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { getAdminTransaction, getAdminTransactions } from '../api/adminApi';
import { ApiError } from '../api/http';
import { useAuth } from '../auth/AuthContext';
import type { AdminTransaction, AdminTransactionDetail } from '../types/adminTransactions';
import { AdminNav } from './AdminDashboardPage';
import './admin-pages.css';
export default function AdminTransactionsPage() { const { user, isAuthenticated, isHydrating, logout } = useAuth(); const navigate = useNavigate(); const [items, setItems] = useState<AdminTransaction[]>([]); const [search, setSearch] = useState(''); const [type, setType] = useState(''); const [status, setStatus] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [page, setPage] = useState(0); const [total, setTotal] = useState(0); const [detail, setDetail] = useState<AdminTransactionDetail | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (user?.role !== 'ADMIN') return; const controller = new AbortController(); getAdminTransactions({ page: String(page), size: '10', sort: 'createdAt,desc', search: search || undefined, type: type || undefined, status: status || undefined, from: from || undefined, to: to || undefined }, controller.signal).then((r) => { setItems(r.content); setTotal(r.totalPages); }).catch((e) => { if (!controller.signal.aborted) { if (e instanceof ApiError && e.status === 401) { logout(); navigate('/login', { replace: true }); } else setError('Transactions could not be loaded.'); } }); return () => controller.abort(); }, [from, logout, navigate, page, search, status, to, type, user?.role]);
  if (isHydrating) return <div className="auth-loading">Restoring your session...</div>; if (!isAuthenticated) return <Navigate to="/login" replace />; if (user?.role !== 'ADMIN') return <Navigate to="/dashboard" replace />;
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setPage(0); setSearch((e.currentTarget.elements.namedItem('search') as HTMLInputElement).value); }
  return <main className="dashboard-shell admin-page"><div className="dashboard-container"><AdminNav active="Transactions" /><section className="admin-page-heading"><span className="dashboard-eyebrow">Read only</span><h1>Transactions</h1></section><form className="admin-filters" onSubmit={submit}><input name="search" defaultValue={search} placeholder="Search email, name, account" /><select value={type} onChange={(e) => { setType(e.target.value); setPage(0); }}><option value="">All types</option><option>DEPOSIT</option><option>WITHDRAW</option><option>TRANSFER_IN</option><option>TRANSFER_OUT</option></select><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(0); }}><option value="">All statuses</option><option>SUCCESS</option><option>FAILED</option><option>CANCELLED</option></select><input type="date" value={from} onChange={(e) => { setFrom(e.target.value); setPage(0); }} aria-label="From date" /><input type="date" value={to} onChange={(e) => { setTo(e.target.value); setPage(0); }} aria-label="To date" /><button className="primary-button" type="submit">Search</button></form>{error && <p className="admin-error">{error}</p>}<section className="admin-panel"><div className="admin-table">{items.map((item) => <div className="admin-row" key={item.transactionId}><span><strong>{item.type}</strong><small>{item.userEmail ?? 'Unknown'} · {item.maskedAccountNumber ?? 'No account'}</small></span><span>{Number(item.amount).toLocaleString('vi-VN')} VND</span><button className="admin-link-button" type="button" onClick={() => getAdminTransaction(item.transactionId).then(setDetail)}>View details</button></div>)}</div><div className="admin-pagination"><button disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page + 1} of {Math.max(total, 1)}</span><button disabled={page + 1 >= total} onClick={() => setPage(page + 1)}>Next</button></div></section></div>{detail && <div className="admin-modal-backdrop" onClick={() => setDetail(null)}><section className="admin-modal" onClick={(e) => e.stopPropagation()}><h2>Transaction #{detail.transactionId}</h2><p>{detail.type} · {detail.status} · journal {detail.journalId ?? 'none'}</p><h3>Ledger entries</h3>{detail.ledgerEntries.map((entry) => <div className="admin-row" key={entry.entryId}><span>{entry.direction} · {entry.ledgerAccountCode}</span><strong>{entry.amount}</strong></div>)}<button className="secondary-button" onClick={() => setDetail(null)}>Close</button></section></div>}</main>;
}
